services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ../db-init:/docker-entrypoint-initdb.d
    networks:
      - server-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    networks:
      - server-network
    volumes:
      - ..:/workspace

networks:
  server-network:
